// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModels.Models
{
    public partial class Dictionary
    {
        public Dictionary()
        {
            ForgetWords = new HashSet<ForgetWords>();
            SynonymsWordId1Navigation = new HashSet<Synonyms>();
            SynonymsWordId2Navigation = new HashSet<Synonyms>();
        }

        public int WordId { get; set; }
        public string WordText { get; set; }
        public string Mean { get; set; }
        public string SpeechPart { get; set; }
        public int? ThemeId { get; set; }
        public int? Level { get; set; }
        public string Author { get; set; }
        public DateTime? DateCreate { get; set; }
        public string Role { get; set; }
        public byte[] IllustrationImg { get; set; }

        public virtual Accounts AuthorNavigation { get; set; }
        public virtual SpeechParts SpeechPartNavigation { get; set; }
        public virtual Themes Theme { get; set; }
        public virtual ICollection<ForgetWords> ForgetWords { get; set; }
        public virtual ICollection<Synonyms> SynonymsWordId1Navigation { get; set; }
        public virtual ICollection<Synonyms> SynonymsWordId2Navigation { get; set; }
    }
}