// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModels.Models
{
    public partial class ForgetWords
    {
        public string ForgetWordId { get; set; }
        public string StudyId { get; set; }
        public string WordId { get; set; }
        public int? ForgetCount { get; set; }

        public virtual Studies Study { get; set; }
        public virtual Dictionary Word { get; set; }
    }
}