// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModels.Models
{
    public partial class SpeechParts
    {
        public SpeechParts()
        {
            Dictionary = new HashSet<Dictionary>();
        }

        public string SpeechPartName { get; set; }
        public string Mean { get; set; }

        public virtual ICollection<Dictionary> Dictionary { get; set; }
    }
}