// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModels.Models
{
    public partial class Studies
    {
        public Studies()
        {
            ForgetWords = new HashSet<ForgetWords>();
        }

        public string StudyId { get; set; }
        public string UserName { get; set; }
        public string ThemeId { get; set; }
        public int? CurrentLevel { get; set; }

        public virtual Accounts UserNameNavigation { get; set; }
        public virtual ICollection<ForgetWords> ForgetWords { get; set; }
    }
}