// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModels.Models
{
    public partial class Synonyms
    {
        public string SynonymId { get; set; }
        public string WordId1 { get; set; }
        public string WordId2 { get; set; }

        public virtual Dictionary WordId1Navigation { get; set; }
        public virtual Dictionary WordId2Navigation { get; set; }
    }
}