// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModels.Models
{
    public partial class Themes
    {
        public Themes()
        {
            Dictionary = new HashSet<Dictionary>();
        }

        public int ThemeId { get; set; }
        public string ThemeName { get; set; }
        public string Mean { get; set; }
        public string Author { get; set; }
        public DateTime? DateCreate { get; set; }
        public DateTime? Lastupdate { get; set; }
        public string Role { get; set; }
        public int? TotalLevel { get; set; }
        public byte[] IllustrationImg { get; set; }

        public virtual Accounts AuthorNavigation { get; set; }
        public virtual ICollection<Dictionary> Dictionary { get; set; }
    }
}