// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModels.Models
{
    public partial class UserInfos
    {
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public int? Age { get; set; }
        public string Sex { get; set; }
        public byte[] AvatarData { get; set; }

        public virtual Accounts UserNameNavigation { get; set; }
    }
}